import { SidebarNav } from "@/components/sidebar-nav";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ApplicationLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="grid grid-cols-4 h-full">
      <div className="border-r hidden md:block col-span-1">
        <SidebarNav />
      </div>
      <div className="col-span-4 md:col-span-3 p-10">{children}</div>
    </section>
  );
}
