import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AuthApplicationLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="grid grid-cols-4 h-full">
      <div className="col-span-4 lmy-10 mx-10 lg:mx-32">{children}</div>
    </section>
  );
}
